package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class purchase_foodController {
	@FXML
	private TextField food_qnty;
	@FXML
	private TextField food_price;
	@FXML
	private TextField food_total_bill;

	 private Stage stage;
	 private Scene scene;
	 private Parent root;
	
	@FXML
	public void buy_btn_fnc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void back_btn_fcn(ActionEvent event) throws IOException {
		root = FXMLLoader.load(getClass().getResource("/application/Main_menu.fxml"));
		  stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		  scene = new Scene(root);
		  stage.setScene(scene);
		  stage.show();
	}
}
